spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url:  jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop    

    

#currencyservice_eurekaurl: http://localhost:8761/eureka
#currencyservice_zipkinurl: http://192.168.99.100:9411/
#currencyservice_configserverurl: http://localhost.100:8888     

currencyservice_eurekaurl: http://192.168.99.100:8761/eureka
currencyservice_zipkinurl: http://192.168.99.100:9411/
currencyservice_configserverurl: http://192.168.99.100:8888      
