   

#currencyservice_eurekaurl: http://localhost:8761/eureka
#currencyservice_zipkinurl: http://192.168.99.100:9411/
#currencyservice_configserverurl: http://localhost.100:8888     

currencyservice_eurekaurl: http://192.168.99.100:8761/eureka
currencyservice_zipkinurl: http://192.168.99.100:9411/
currencyservice_configserverurl: http://192.168.99.100:8888      
