spring:
  cloud:   
   gateway:
      routes:
      - id: CurrencyExchangeService
        uri: lb://CurrencyExchangeService
        predicates:
        - Path=/currencyexchange/**
      - id: CurrencyConversionFactorService
        uri: lb://CurrencyConversionFactorService
        predicates:
        - Path=/currencyconversionfactor/** 

