--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: nginx
  name: nginx
  namespace: demo
spec: 
  ports: 
    - 
      name: http
      port: 80
      targetPort: 80
  selector: 
    run: nginx
  type: NodePort # LoadBalancer | ClusterIP | https://kubernetes.io/docs/concepts/services-networking/service/